# Legal Jargons Dictionary - Maps legal terms to their simplified meanings
LEGAL_JARGONS = {
    # Contract Terms
    "Agreement": "A deal or contract between two or more parties",
    "Consideration": "Something of value exchanged in a contract (money, services, etc.)",
    "Breach": "Breaking or violating the terms of a contract",
    "Termination": "Ending or canceling a contract",
    "Amendment": "A change or addition to an existing contract",
    "Addendum": "An extra document added to a contract with additional terms",
    "Covenant": "A formal promise or agreement in a contract",
    "Indemnify": "To protect someone from financial loss or legal responsibility",
    "Indemnification": "Protection from financial loss or legal responsibility",
    "Liability": "Legal responsibility for something, especially damages or debts",
    "Damages": "Money paid as compensation for loss or injury",
    "Remedy": "A solution or way to fix a legal problem",
    "Default": "Failure to meet the obligations of a contract",
    "Force Majeure": "Unforeseeable events (like natural disasters) that prevent contract fulfillment",
    "Mutual Agreement": "When all parties agree to the same terms",
    "Unilateral": "Action taken by only one party",
    "Bilateral": "Agreement involving two parties",
    "Multilateral": "Agreement involving more than two parties",
    
    # Legal Procedures
    "Whereas": "A formal way to say 'considering that' or 'given that'",
    "Hereby": "By this document or action",
    "Herein": "In this document",
    "Hereafter": "From this point forward",
    "Heretofore": "Up until now",
    "Pursuant": "According to or in accordance with",
    "Notwithstanding": "Despite or regardless of",
    "Aforementioned": "Previously mentioned",
    "Aforesaid": "Said or mentioned before",
    "Shall": "Must or is required to",
    "May": "Has permission to or is allowed to",
    "Severability": "If one part of a contract is invalid, the rest remains valid",
    
    # Business Terms
    "Intellectual Property": "Creations of the mind like inventions, designs, or brand names",
    "Confidentiality": "Keeping information secret or private",
    "Non-disclosure": "Agreement not to share confidential information",
    "Proprietary": "Owned by a particular company or person",
    "Trademark": "A symbol, word, or phrase that identifies a brand",
    "Copyright": "Legal right to control the use of creative works",
    "Patent": "Exclusive right to make, use, or sell an invention",
    "Trade Secret": "Confidential business information that gives a competitive advantage",
    "Due Diligence": "Careful investigation or research before making a decision",
    "Goodwill": "The reputation and customer relationships of a business",
    "Subsidiary": "A company controlled by another larger company",
    "Affiliate": "A company connected to or associated with another company",
    
    # Financial Terms
    "Escrow": "Money held by a neutral third party until conditions are met",
    "Collateral": "Property used as security for a loan",
    "Lien": "A legal claim on property until a debt is paid",
    "Mortgage": "A loan secured by real estate property",
    "Guarantee": "A promise to pay if someone else fails to pay",
    "Security": "Something pledged as protection for a loan",
    "Principal": "The original amount of money lent or invested",
    "Interest": "Money charged for borrowing money",
    "Compound Interest": "Interest calculated on both principal and previously earned interest",
    "Amortization": "Gradual payment of a debt over time",
    
    # Employment Terms
    "At-Will Employment": "Employment that can be ended by either party at any time",
    "Wrongful Termination": "Firing someone for illegal reasons",
    "Non-Compete": "Agreement not to work for competitors for a certain period",
    "Non-Solicitation": "Agreement not to recruit former colleagues or clients",
    "Severance": "Payment made to an employee when they are laid off",
    "Vesting": "Earning the right to receive benefits over time",
    "Stock Options": "The right to buy company shares at a fixed price",
    
    # Real Estate Terms
    "Title": "Legal ownership of property",
    "Deed": "Legal document that transfers ownership of property",
    "Easement": "Right to use someone else's property for a specific purpose",
    "Zoning": "Laws that control how land can be used",
    "Appraisal": "Professional estimate of property value",
    "Closing": "Final step in a real estate transaction",
    "Contingency": "Condition that must be met for a contract to be valid",
    
    # Legal Status Terms
    "Plaintiff": "Person who brings a legal case against another",
    "Defendant": "Person being sued or accused in a legal case",
    "Jurisdiction": "Area where a court has authority to make legal decisions",
    "Venue": "The location where a legal case is heard",
    "Statute of Limitations": "Time limit for filing a legal claim",
    "Precedent": "Previous court decision that guides future similar cases",
    "Injunction": "Court order requiring someone to do or stop doing something",
    "Subpoena": "Legal order requiring someone to appear in court or provide documents",
    "Deposition": "Sworn testimony given outside of court",
    "Arbitration": "Settling a dispute outside of court with a neutral decision-maker",
    "Mediation": "Negotiation process with a neutral person helping reach agreement",
    
    # Insurance Terms
    "Premium": "Regular payment made to keep insurance coverage",
    "Deductible": "Amount you pay before insurance covers the rest",
    "Coverage": "Protection provided by an insurance policy",
    "Claim": "Request for payment from an insurance company",
    "Exclusion": "Something not covered by an insurance policy",
    "Rider": "Additional coverage added to an insurance policy",
    
    # Tax Terms
    "Withholding": "Money taken from wages for taxes",
    "Exemption": "Income that is not subject to tax",
    "Deduction": "Amount subtracted from taxable income",
    "Credit": "Amount subtracted directly from taxes owed",
    "Audit": "Official examination of financial records",
    
    # Miscellaneous Legal Terms
    "Pro Rata": "Proportional or in equal shares",
    "Bona Fide": "Genuine or made in good faith",
    "Prima Facie": "At first appearance or on the face of it",
    "Quid Pro Quo": "Something given in exchange for something else",
    "Status Quo": "The existing state of things",
    "Per Se": "By itself or inherently",
    "Ad Hoc": "Created for a specific purpose",
    "In Lieu Of": "Instead of or in place of",
    "Waiver": "Giving up a right or claim",
    "Estoppel": "Preventing someone from arguing something contrary to previous actions",
    "Fiduciary": "Person legally required to act in another's best interest",
    "Power of Attorney": "Legal authority to act on someone else's behalf",
    "Guardian": "Person legally responsible for another person's affairs",
    "Executor": "Person responsible for carrying out a will",
    "Beneficiary": "Person who receives benefits from a will, trust, or insurance policy"
}